[package]
name = "vessel"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# 更多键及其定义请参阅 https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# `_lib` 后缀可能看起来多余，但它是必要的
# 以使库名称唯一，且不会与二进制文件名称冲突。
# 这似乎只是 Windows 上的问题，见 https://github.com/rust-lang/cargo/issues/8519
name = "docker_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
tauri-plugin-opener = "2"
tauri-plugin-autostart = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bollard = "0.17"
winapi = { version = "0.3", features = ["winerror"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "sqlite"] }
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1.0.102"
once_cell = "1.19"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tower-service = "0.3"
pin-project = "1.1"
http-body-util = "0.1"
futures-util = "0.3"

